source 'https://rubygems.org'

gem 'bcrypt-ruby', require: 'bcrypt'
gem 'bourbon'
gem 'coffee-rails', '~> 4.1.0'
gem 'haml-rails'
gem 'google-webfonts-rails'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'neat'
gem 'pg'
gem 'rails', '4.2.2'
gem 'sass-rails', '~> 5.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'uglifier', '>= 1.3.0'
